{% set name = "holidays-ext" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/holidays-ext-{{ version }}.tar.gz
  sha256: b2f80051dc3191262b9a95a6c625427a53a50814b0f162a87fdb22fccf978090

build:
  skip: True  # [s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - numpy >=1.15.4
    - pandas >=1.0.4
    - python-dateutil >=2.8.0
    - lunarcalendar-ext >=0.0.1
    - convertdate >=2.1.2
    - holidays >=0.9.5

test:
  imports:
    - holidays_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kaixuyang/holidays-extension
  summary: Extended holidays package
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/kaixuyang/holidays-extension
  doc_url: https://github.com/dr-prodigy/python-holidays/blob/beta/README.rst
  description: This repo forks the Facebook Prophet library, and serve as an extension of the Python holidays library. The holidays are customized and extended.

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
